version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Upserting SageMaker Pipeline: TradeOffBiasVariance"
      - python src/upsert_pipeline.py

artifacts:
  files:
    - '**/*'
