version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"
    S3_ARTIFACT_BUCKET: "iris-mlops-artifacts"
    SAGEMAKER_EXECUTION_ROLE_ARN: "arn:aws:iam::123456789012:role/SageMakerExecutionRole"
    SAGEMAKER_BASE_JOB_PREFIX: "iris-mlops"
    ACCOUNT_ID: "503427799533"

phases:
  install:
    commands:
      - echo "=== Instalando dependencias base para CodeBuild ==="
      - python -m pip install --upgrade pip
      - pip install sagemaker boto3

  pre_build:
    commands:
      - echo "Autenticando en Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo "=== Construyendo imagen Docker con Kedro ==="
      - docker build -t iris-mlops .
      # Validación: que se pueda importar el paquete
      - docker run --rm iris-mlops python -c "import kedro; print('kedro OK')"
      - docker tag iris-mlops:latest $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/iris-mlops:latest

  post_build:
    commands:
      - echo "Empujando imagen a ECR..."
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/iris-mlops:latest
      - echo "Imagen subida a ECR correctamente"
      - echo "Ejecutando pipeline en SageMaker..."
      - python src/tradeoff_pipeline.py

artifacts:
  files:
    - '**/*'
